<?php

namespace Modules\Shop\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Modules\Category\Models\Category;
use LamaLama\Wishlist\Wishlistable;
use Modules\Location\Models\Location;
use Modules\Media\Helpers\FileHelper;
use Modules\Tag\Models\Tag;

class Shop extends Model
{
    use Wishlistable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'title',
        'description',
        'status',
        'create_user',
        'update_user',
        'days',
        'video',
        'gallery',
        'image_id',
        'featured_mobile',
        'location_id',
        'phone_number',
        'title_ar',
        'description_ar',
        'lat',
        'lng',
        'is_main_branch',
        'main_branch_id',
        'type',
        'website_link', 
        'insta_link',
        'facebook_link',
        'source_id'
    ];

    protected $slugField     = 'slug';
    protected $slugFromField = 'title';

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    // protected $casts = [
    //     'email_verified_at' => 'datetime',
    // ];


    public function category_shops()
    {
        return $this->belongsToMany(Category::class,
            "shop_has_categories",
            "shop_id",
            "category_id")->withPivot('category_id');
    }

    public function save(array $options = [])
    {
        $this->featured_image = $this->getFeaturedImage()[0]['featured_mobile'] ?? $this->featured_image;
        if ($this->create_user) {
            $this->update_user = Auth::id();
        } else {
            $this->create_user = Auth::id();
        }
        if ($this->slugField && $this->slugFromField) {
            $slugField = $this->slugField;
            $this->$slugField = $this->generateSlug($this->$slugField);
        }
        // dd($options);
        return parent::save($options); // TODO: Change the autogenerated stub
    }


    public function generateSlug($string = false, $count = 0)
    {
        $slugFromField = $this->slugFromField;
        if (empty($string))
            $string = $this->$slugFromField;
        $slug = $newSlug = $this->strToSlug($string);
        $newSlug = $slug . ($count ? '-' . $count : '');
        $model = static::select('count(id)');
        if ($this->id) {
            $model->where('id', '<>', $this->id);
        }
        $check = $model->where($this->slugField, $newSlug)->count();
        if (!empty($check)) {
            return $this->generateSlug($slug, $count + 1);
        }
        return $newSlug;
    }

    // Add Support for non-ascii string
    // Example বাংলাদেশ   ব্যাংকের    রিজার্ভের  অর্থ  চুরির   ঘটনায়   ফিলিপাইনের
    protected function strToSlug($string) {
        $slug = Str::slug($string);
        if(empty($slug)){
            $slug = preg_replace('/\s+/u', '-', trim($string));
        }
        return $slug;
    }

    public function getGallery($featuredIncluded = false)
    {
        if (empty($this->gallery))
            return $this->gallery;
        $list_item = [];
        if ($featuredIncluded and $this->image_id) {
            $list_item[] = [
                'large' => str_replace(['.png', '.jpg', '.jpeg'], '.webp', FileHelper::url($this->image_id, 'full')),
                'thumb' => FileHelper::url($this->image_id, 'thumb')
            ];
        }

        $items = explode(",", $this->gallery);
        foreach ($items as $k => $item) {
            if ($item) {
                $large =  FileHelper::url($item, 'full');
                $thumb = FileHelper::url($item, 'thumb');
                $medium = FileHelper::url($item, 'medium');

                $list_item[] = [
                    'large' => $large,
                    'thumb' => $thumb,
                    'medium'=>$medium
                ];
            }
        }
        return $list_item;
    }

    public function getFeaturedImage()
    {
        if (empty($this->image_id))
            return $this->image_id;
        $list_item = [];
        if ($this->image_id) {
            $list_item[] = [
                'featured_mobile' => FileHelper::url($this->image_id, 'full'),
                'featured_web' => FileHelper::url($this->image_id, 'thumb'),

            ];
        }
        return $list_item;
    }
    
    /*
    * Get meta
    *
    * @return \Illuminate\Database\Eloquent\Relations\HasOne
    */
   public function meta()
   {
       return $this->hasOne(ShopMeta::class, "shop_id", 'id');
   }

   public function location()
   {
        return $this->belongsTo(Location::class, 'id', 'shop_id');
   }

   public function isWished()
   {
       return DB::table('wishlist')
           ->where('user_id', Auth::id())
           ->where('model_id', $this->id)
           ->first();
   }

   public function isWishList()
   {
       if (Auth::id()) {
           if (!empty($this->isWished()) and !empty($this->isWished()->id)) {
               return '-solid';
           }
       }
       return '';
   }

   public function tag_shops()
    {
        return $this->belongsToMany(Tag::class,
            "shop_has_tags",
            "shop_id",
            "tag_id")->withPivot('tag_id');
    }

}
