<?php
namespace Modules\Media\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Modules\Media\Database\factories\MediaFileFactory;

class MediaFile extends Model
{
    use SoftDeletes;
    use HasFactory;
    protected $table = 'media_files';

    protected $fillable = [
        'file_name',
        'file_path',
        'file_size',
        'file_type',
        'file_extension',
        'file_width',
        'file_heights',
        'create_user'
    ];

    protected static function newFactory()
    {
        return MediaFileFactory::new();
    }

    public static function findMediaByName($name)
    {
        return MediaFile::where("file_name", $name)->firstOrFail();
    }

    public function cacheKey()
    {
        return sprintf("%s/%s", $this->getTable(), $this->getKey());
    }

    public function findById($id)
    {
        return Cache::rememberForever($this->cacheKey() . ':' . $id, function () use ($id) {
            return $this->find($id);
        });
    }

    public function save(array $options = [])
    {
        if ($this->create_user) {
            $this->update_user = Auth::id();
        } else {
            $this->create_user = Auth::id();
        }
        
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
